version: '3.8'

services:
  dynamic-proxy:
    build: .
    container_name: dynamic-proxy
    ports:
      - "17283:17283"  # SOCKS5 Strict (SSL verification enabled)
      - "17284:17284"  # SOCKS5 Relaxed (SSL verification disabled)
      - "17285:17285"  # HTTP Strict (SSL verification enabled)
      - "17286:17286"  # HTTP Relaxed (SSL verification disabled)
    volumes:
      - ./config.yaml:/app/config.yaml:ro  # Mount config as read-only
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai  # Set timezone (optional)
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
