name: Docker Build and Publish

on:
  push:
    branches: [ "main" ] # 当推送到 main 分支时触发
    # tags: [ 'v*.*.*' ] # (可选) 当推送到 v1.0.0 格式的 tag 时触发
  pull_request:
    branches: [ "main" ]

env:
  # 使用 GitHub 的官方仓库地址
  REGISTRY: ghcr.io
  # 镜像名称默认使用 <用户名>/<仓库名>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 允许写入 GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Docker Buildx 环境 (用于构建多架构镜像或更好的缓存)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到 GitHub Container Registry
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 自动提取 metadata (tags, labels)
      # 这会自动处理 tag，例如 main 分支会打上 :main 和 :latest 标签
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 构建并推送镜像
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # PR 只构建不推送，Push 才推送
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # 使用 GitHub Actions 缓存加速构建
          cache-to: type=gha,mode=max
